variables:
  COVERAGE: "true"
  PG_VERSION: "9.6"
  RUBY_IMAGE_VERSION: "latest"

setup:
  extends: .setup

rubocop:
  extends: .rubocop

brakeman:
  extends: .brakeman
  script: bundle exec brakeman spec/dummy

rspec:
  extends:
    - .base-rails # Dummy Rails application
    - .rspec-all
  before_script:
    - cp ./spec/dummy/config/database.ci.yml ./spec/dummy/config/database.yml
    - cd spec/dummy
    - bundle exec rake db:create db:migrate

include:
  - project: 'cm_tech/cm_shared'
    ref: shared_gitlab_ci
    file: '/.gitlab/ci/defaults.yml'
