variables:
  COVERAGE: "true"
  PG_VERSION: "9.6"
  RUBY_IMAGE_VERSION: "2.6.3buster"

setup:
  extends: .setup

rubocop:
  extends: .rubocop

brakeman:
  extends: .brakeman

rspec:
  extends:
    - .rspec-all
    - .service-postgres

include:
  - project: 'cm_tech/cm_shared'
    ref: shared_gitlab_ci
    file: '/.gitlab/ci/defaults.yml'
